service: 'aws-nodejs-typescript'
org: "tomoki"
app: "aws-nodejs-typescript"
frameworkVersion: '2'
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: 
      - 'aws-sdk'
    target: 'node14'
    # define:
    #   require.resolve: undefined
    platform: 'node'
plugins: 
  - serverless-esbuild
provider:
  name: 'aws'
  runtime: 'nodejs14.x'
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
  lambdaHashingVersion: '20201221'
functions:
  hello:
    handler: src/functions/index.hello
